### PR TITLE
Persist panel layout

### LINKED ISSUE #20: Persist Panel Layout

### PR DESCRIPTION
**Pull request by raujonas**
This is my suggestion to persist the panel layout, would close #20.

grafik

- The location and dimensions of the main window is stored separate from the connections. It is updated when the application is closed and loaded on startup. Works also with multiple monitors.
- The panel layout of the connection view is stored for each connection. Because it was difficult to listen for changes of the splitpane dividers (the UI froze because there were too many updates to store on disk while adjusting the divider) I thought it would be better to tell when you're happy with the layout by hitting a save button and then save all necessary values together. There's now one button for saving and one for restoring the default layout which must be saved after.

Thougts? :eyes:

### CODE REVIEW

**Comment by farion** [comment]
Great. Works good.

My thoughts to the layout per connection thing:
- Basically such banal things like the layout persistence is something a user should not be forced to think about. Freely adapted from Apple, we know what is good for you. Usually I do not like this attitude, but in this case I would prefer it. This feature is very important to make people happy, but the buttons in the toolbar steals user focus from thing he must care about.
- Why not save the layout for a connection when either the tab is closed or the application exits automatically. So I will only lose my layout in cases where the application crashes ... which won't happen for correo of course :).
- Of course this will drop the feature to reset a layout to factory settings. Here I would introduce a new menu called "View". It contains the existing functionality to hide and show the pub/sub panels (three points) and the possibility to reset the layout "Reset Layout for current connection".

What do you think? @raujonas

**Comment by raujonas** [comment]
Sounds good. To summarize it:
- I will remove the buttons and store the layout only on application exit or connection tab close.
- Introduce new menu for selecting panels and reset layout.

This means if the application is closed by the user, I have to iterate over each open connection tab and store the layout, right? @farion

**Comment by farion** [comment]
@raujonas Yes, exactly. And thanks for doing this ;P

**Comment by raujonas** [comment]
grafik

@farion these buttons should also be removed and added to the new menu, right?

**Comment by raujonas** [comment]
publish

@farion how do you like the icons in front of the menu items? Should I add icons for the menu items in the other menus too maybe?

**Comment by raujonas** [comment]
@farion now it's finally ready for review, re-added the buttons:
grafik

Should I add icons for the other menu items in the other menus too?

**Pull request merged**
