### PR TITLE
Support formatting of the publish textarea (closes #19)

### LINKED ISSUE #19: Support formatting of the publish textarea
When writing JSON or XML the textarea should support syntax highlighting and automatic formatting.

### PR DESCRIPTION
**Pull request by raujonas**
grafik

The publish text area now supports syntax highlighting for json and xml with the same behavior as the detail view (automatic formatting if possible, toggle button removes format): closes #19 

**Note**: If debug log messages are included in the log, the json format plugin produces very long error messages if the input cannot be parsed as json. Because the format is checked with each new letter typed in the publish text area, this can result in small lags if you're typing fast.

```
13:45:41,603 [DEBUG] [.p.f.JsonFormat] [          ] JSON could not be parsed. com.fasterxml.jackson.core.JsonParseException: Unexpected character ('s' (code 115)): was expecting comma to separate Object entries
...
...
...
```
If I disable the logging of debug messages in the logger configuration there is no lag while typing. So maybe we should remove the logging of the exception in the json plugin or disable logging debug messages with the next release.
```
private Object createJsonObject() {
        try {
            ObjectMapper objectMapper = new ObjectMapper();
            objectMapper.configure(MapperFeature.CAN_OVERRIDE_ACCESS_MODIFIERS, false);
            jsonObject = objectMapper.readValue(text, Object.class);
        } catch (IOException e) {
            LOGGER.debug("JSON could not be parsed. ", e);
            return null;
        }
        return jsonObject;
    }
```

### CODE REVIEW

**Comment by farion** [comment]
- I would propose to set the log here to trace.
- Currently the format button disables the formatting only for the current moment. As soon as I type it rechecks and formats as soon as I formatted something correct. Maybe it would be better to disable the formatting and the detection completely as long as the button is disabled.
@raujonas

**Comment by raujonas** [comment]
- I will set the log to trace in the plugin and make a new PR over there. 
- Should the formatting be turned on per default? Then the user can disable it -> it should stay disabled until the re-enables it manually like you proposed, sounds good! Is this correct @farion ?

**Comment by farion** [comment]
@raujonas Yes exactly. On per default.

**Comment by raujonas** [comment]
@farion please check again, already rebased onto develop. Plugin changes are here: https://github.com/EXXETA/correomqtt-plugin-json-format/pull/3

**Pull request merged**
